name: 'Your name here'
description: 'Provide a description here'
author: 'Your name or organization here'
inputs:
  owner:
    description: The user to create the deployment
    required: true
  ref:
    description: The ref to deploy. This can be a branch, tag, or SHA.
    required: true
  environment:
    description: Name for the target deployment environment (e.g., `production`, `staging`, `qa`).
    required: true
  payload:
    description: JSON string to include in the deployment payload.
    required: false
runs:
  using: 'node12'
  main: 'lib/main.js'
