name: 'Create Deployment'
description: 'Create a GitHub deployment'
inputs:
  owner:
    description: The owner of the repository
    required: true
  repo:
    description: The repository name
    required: true
  ref:
    description: The ref to deploy. This can be a branch, tag, or SHA.
    required: true
  task:
    description: Deployment task
    required: false
    default: deploy:github
  environment:
    description: Name for the target deployment environment (e.g., `production`, `staging`, `qa`).
    required: true
  application:
    description: Name of the target application
    required: false
    default: ''
  values_file:
    description: File path relative to the root of the deployment repo containing the helm values file
    required: false
    default: ''
  key_paths:
    description: Comma separated string of paths to keys in the values file
    required: false
    default: ''
runs:
  using: 'node12'
  main: 'lib/main.js'
